repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v6.0.0"
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.21.2
    hooks:
    - id: pyupgrade
      args: [--py314-plus]
  - repo: local
    hooks:
      - id: doit
        name: doit
        description: "Run builds & tests"
        entry: doit
        language: python
        always_run: true # doit has its own DAG, no worries
        pass_filenames: false
