default_install_hook_types: ["pre-commit", "pre-push"]
repos:
  # General fixes
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v6.0.0"
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.21.2
    hooks:
      - id: pyupgrade
        args: [--py314-plus]
  # Typst formatting
  - repo: https://github.com/typstyle-rs/pre-commit-typstyle
    rev: "v0.14.4"
    hooks:
      - id: typstyle
        args: ["-i", "--line-width", "90", "--wrap-text", "--"]
  # Python linting & formatting
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.18
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/DetachHead/basedpyright-prek-mirror
    rev: 1.39.8
    hooks:
      - id: basedpyright
        additional_dependencies: &python-dependencies
          - doit>=0.37.0
          - cyclopts>=4.19.0
          - pyyaml>=6.0.3
        pass_filenames: false
  # Project building
  - repo: local
    hooks:
      - id: doit
        name: doit
        description: "Run builds & tests"
        entry: doit
        language: python
        always_run: true # doit has its own DAG, no worries
        additional_dependencies: *python-dependencies
        pass_filenames: false
