repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v6.0.0"
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.21.2
    hooks:
    - id: pyupgrade
      args: [--py314-plus]
  - repo: https://github.com/typstyle-rs/pre-commit-typstyle
    rev: "v0.14.4"
    hooks: [{id: typstyle}]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.15.10
    hooks:
      # Run the linter.
      - id: ruff-check
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format
  - repo: local
    hooks:
      - id: doit
        name: doit
        description: "Run builds & tests"
        entry: doit
        language: python
        always_run: true # doit has its own DAG, no worries
        pass_filenames: false
